documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/README.md'
          - '**/docs/**/*'

github-actions:
  - changed-files:
      - any-glob-to-any-file:
          - '**/.github/workflows/*'
          - '**/.github/workflows/**/*'
          - '**/.github/dependabot.yaml'
          - '**/.github/pull_request_labeler.yaml'

github-templates:
  - changed-files:
      - any-glob-to-any-file:
          - '**/.github/ISSUE_TEMPLATE/*'
          - '**/.github/PULL_REQUEST_TEMPLATE.md'
          - '**/.github/.chglog/*'
          - '**/.github/.chglog/**/*'

internal:
  - changed-files:
      - any-glob-to-any-file:
          - '**/.gitignore'
          - '**/.pre-commit-config.yaml'
          - '**/MANIFEST.in'
          - '**/Makefile'
          - '**/CONTRIBUTING.md'
          - '**/MAINTAINERS.md'
          - '**/CODE_OF_CONDUCT.md'
          - '**/LICENSE'
          - '**/THIRD-PARTY-LICENSES'
          - '**/.editorconfig'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - '**/go.mod'
          - '**/go.sum'

go:
  - changed-files:
      - any-glob-to-any-file: '**/*.go'

markdown:
  - changed-files:
      - any-glob-to-any-file: '**/*.md'
