name: Test
on:
  push:
    branches:
      - "!release"
  pull_request:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
          check-latest: true
      - name: Run go build
        run: go build ./...
      - name: Run go test
        run: go test -race ./...
